package com.augmentedsociety.myphr.presentation.vitalsigns;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.Context;
import android.content.DialogInterface;
import android.content.Intent;
import android.view.View;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import com.augmentedsociety.myphr.R;
import com.augmentedsociety.myphr.domain.BloodSugarMapper;
import com.augmentedsociety.myphr.domain.BloodSugarReading;
import com.augmentedsociety.myphr.domain.MapperException;
import com.augmentedsociety.myphr.domain.ReadingSource;
import com.augmentedsociety.myphr.domain.WeightMapper;
import com.augmentedsociety.myphr.domain.WeightReading;
import com.augmentedsociety.myphr.domain.logs.LogEventType;
import com.augmentedsociety.myphr.presentation.SpeechHelp;
import com.augmentedsociety.myphr.presentation.customviews.SquareImageButton;
import com.augmentedsociety.myphr.presentation.logs.LogEventEmitter;

/**
 * Weight Activity class for user inputs
 * 
 * @author Serge-Antoine
 * 
 */

public class WeightActivity extends VitalSignComponent
{
	/**
	 * The following instantiations allow an instance of a controller to take the
	 * arguments generated by this activity in order for the controller itself to
	 * submit the data the the proper mapper via the commands package for
	 * compilation, determined by the VITAL_SIGN string's value
	 */
	private VitalSignsController mController = new VitalSignsController();
	private static final String VITAL_SIGN = "Weight";
	private WeightReading mBluetoothReading = null;
	private static final int REQUEST_ENABLE_BT = 1;
//	private static WeightActivity weightActivity;
	private static boolean savedSuccessful = false;
	private final String WEIGHT = "bodyWeight";
	protected boolean isDataValid = false;//fh


	public WeightActivity(Activity mAct)
	{
		super(mAct);
		mAct.setTitle("Weight");
		
		EditText t = (EditText) mAct.findViewById(R.id.weight_value);
		t.setSelection(t.getText().length());
		
		SpeechHelp tut = SpeechHelp.getInstance();
		if(tut.isActive())
		{
			tut.playTutorial(mAct, WEIGHT);
		}
		else
		{
			tut.stopTutorial();
		}
	}
	

	/**
	 * Handles the "submit"/manual button press; if a Bluetooth reading was
	 * performed, this method will automatically be aware of it and handle it
	 * correctly in a "Bluetooth context entry" for the commands to the mapper
	 * i.e. saved as Bluetooth reading in the DB.
	 */
	public void submit(View iView, Date timeOfReading, boolean lastActivity)
	{
		/**
		 * An object created by bluetooth reading will have BLUETOOTH as a
		 * ReadingSource.
		 */
	//fh
			if (null != mBluetoothReading
					&& ReadingSource.BLUETOOTH == mBluetoothReading.getMeasurementSource())
			{
				/* Get the view's current context for proper detection of activity launch */
				Context context = iView.getContext();
	
				/* References to text box values */
				TextView t = (TextView) mAct.findViewById(R.id.weight_value);
				String tText = t.getText().toString();
				if (!tText.isEmpty())
				{
					float weight = Float.valueOf(t.getText().toString());
	
					try
					{
						/**
						 * Since the WeightReading has already been instantiated by the
						 * external BluetoothDevice mapper, it is passed directly to the
						 * WeightMapper, without having to go through controller and command
						 * for VitalSignObject instantiation.
						 */
						WeightMapper.insert(mBluetoothReading, context);
	
						/* Fires a LogEvent to the LogItemEditor */
						LogEventEmitter.fireLogEvent(this, iView.getContext(),
								LogEventType.VS_TEMP_CREATE);
	
						/*
						 * Calls a short text box confirming data save. Should not occur if an
						 * exception should be caught inside mappers
						 */
	//					Toast.makeText(context, context.getString(R.string.confirm_save),
	//							Toast.LENGTH_SHORT).show();
						savedSuccessful = true;
						VitalSignsActivity.hasBeenSaved = true;//fh
						if (lastActivity){
							saveMethod(t);
						}
						
						/*
						 * After data save, text box values are reset and focus is placed to
						 * the first entry of the page list
						 */
						t = (TextView) mAct.findViewById(R.id.weight_value);
						t.setText(null);
	
						mAct.findViewById(R.id.weight_value).requestFocus((int) weight, null);
					} catch (MapperException e)
					{
						Toast.makeText(context, e.getMessage(), Toast.LENGTH_LONG).show();
					}
				} else
				{
	//				Toast.makeText(context, context.getString(R.string.prompt_save_again),
	//						Toast.LENGTH_LONG).show();
					savedSuccessful = false;
				}
			} else
			{
				/** Get the view's current context for proper detection of activity launch */
				Context context = iView.getContext();
	
				/** References to text box values */
				TextView t = (TextView) mAct.findViewById(R.id.weight_value);
				String tText = t.getText().toString();
				if (!tText.isEmpty())
				{
					float weight = Float.valueOf(t.getText().toString());
	//				Date timeOfReading = getDateValue(R.id.datePickerWeight,
	//						R.id.timePickerWeight);
	
					/*
					 * Controller passes user inputs to right mapper via commands package;
					 * data then processed into database upon successful entry.
					 */
					mController.manipulate(weight, timeOfReading, VITAL_SIGN,
							ReadingSource.KEYED, context);
	
					/* Fires a LogEvent to the LogItemEditor */
					LogEventEmitter.fireLogEvent(this, iView.getContext(),
							LogEventType.VS_TEMP_CREATE);
	
					/*
					 * Calls a short text box confirming data save. Should not occur if an
					 * exception should be caught inside mappers
					 */
	//				Toast.makeText(context, context.getString(R.string.confirm_save),
	//						Toast.LENGTH_SHORT).show();
					savedSuccessful = true;
					VitalSignsActivity.hasBeenSaved = true;//fh
					if (lastActivity){
						saveMethod(t);
					}
					
					/*
					 * After data save, text box values are reset and focus is placed to the
					 * first entry of the page list
					 */
					t = (TextView) mAct.findViewById(R.id.weight_value);
					t.setText(null);
	
					mAct.findViewById(R.id.weight_value).requestFocus((int) weight, null);
				} else
				{
	//				Toast.makeText(context, context.getString(R.string.prompt_save_again),
	//						Toast.LENGTH_LONG).show();
					savedSuccessful = false;
				}
			}
	}
	
	public static boolean getSavedSuccessful()
	{
		return savedSuccessful;
	}

	/**
	 * Handles the "Bluetooth" button press
	 */
	public void bluetooth(View iView)
	{
		msgbox("Bluetooth-enabled weight reader feature not yet implemented.",
				"Notice");
	}

	protected void msgbox(String iMessage, String iTitle)
	{
		AlertDialog.Builder dlgAlert = new AlertDialog.Builder(mAct); // mAct: you
																																	// may want to
																																	// replace
																																	// with 'this'
																																	// if you move
																																	// this method
		dlgAlert.setMessage(iMessage);
		dlgAlert.setTitle(iTitle);
		dlgAlert.setPositiveButton("OK", null);
		dlgAlert.setCancelable(true);
		dlgAlert.create().show();
	}

	protected void onActivityResult(int iRequestCode, int iResultCode,
			Intent iData)
	{
		if (iRequestCode == REQUEST_ENABLE_BT)
		{
			if (iResultCode == Activity.RESULT_OK) // mAct: you may want to remove it
																							// if you move this method
			{
				msgbox("Bluetooth has been successfully enabled!", "Success");
				bluetooth(null);
			} else
				msgbox("Please enable Bluetooth to allow communicating to the device.",
						"Message");
		} else
		{
			msgbox("TemperatureActivity: Unknown request code: " + iRequestCode,
					"Error");
		}
	}

	public void finish(View iView)
	{
		// return to previous view
		mAct.finish();
	}

	public void preparePageTransition()
	{
		if (((SquareImageButton) (VitalSignsActivity.VITAL_SIGN_ACTIVITY
				.findViewById(R.id.body_weight))).isShown())
			showKeyboard();
		setTextFieldFocus(R.id.weight_value);
		createNextPageListener(R.id.weight_value);
		
	}
	protected void validateData(View iView){//fh
    //create state
    Context iContext = iView.getContext();
 
		if (this != null){
				try
				{
				// Get today as a Calendar  
					Calendar today = Calendar.getInstance();  
					// Subtract 1 day  
					today.add(Calendar.DATE, -7);  
					// Make an SQL Date out of that  
					Date lastSevenDays = new java.sql.Date(today.getTimeInMillis());
					ArrayList<WeightReading> result = WeightMapper.findLastSevenDays(lastSevenDays, iContext);
					TextView t = (TextView) mAct.findViewById(R.id.weight_value);
					
					float tWeight = Float.valueOf(t.getText().toString());
					   
				  int averageWeight = 0;
				  for (WeightReading bp: result){	
				  	averageWeight += bp.getWeight();
				  }
				  if (result.size() ==0){
				  	isDataValid=true;
				  	return;
				  }
				  averageWeight=averageWeight/result.size();
				  
				  float diff=0;
				  boolean diffWeight = false;
				   
				  if (averageWeight == tWeight){
				  	diff=0;
				  } else if (averageWeight > tWeight){
				  	 diff = averageWeight - tWeight;
				  } else if (averageWeight < tWeight){
				  	 diff = tWeight-averageWeight;
				  }
				  if (diff >= 0.68){
				  	diffWeight = true;
				  }
				  
				  if (diffWeight){
				  	isDataValid = false;
				  }else {
				  	isDataValid= true;
				  }
				  

				} catch (MapperException e)
				{
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			
		}
		//fh
	}
}
